---
services:
  vaping:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vaping
    image: vaping
    network_mode: host
    restart: unless-stopped
    secrets:
      - "SECRET="
    volumes:
      - source: config/config.yaml
        target: /opt/vaping/config.yaml
        type: bind
