---
services:
  container-vaping:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container-vaping
    image: container-vaping
    network_mode: host
    restart: unless-stopped
    secrets:
      - "SECRET="
    volumes:
      - source: config/config.yaml
        target: /opt/container-vaping/config.yaml
        type: bind
