---
jobs:
  image:
    name: Image
    secrets: inherit
    uses: MattKobayashi/actions-workflows/.github/workflows/publish.yaml@6d5381b1c1fe60d9610f099a5bcafd9ceab20782 # v1.0.2
    with:
      image-name: vaping
name: Publish
on:
  release:
    types:
      - published
  workflow_dispatch:
permissions:
  contents: read
  packages: write
